version: '3'

services:
  mariadb:
    container_name: mariadb-container-data-feed
    image: mariadb:${MARIADB_VERSION}
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: